# Generated by Django 3.0.5 on 2021-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20210301_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('delayed', 'Delayed'), ('not started', 'Not Started')], default='', max_length=50),
        ),
    ]
