# Generated by Django 3.0.5 on 2021-03-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210325_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='end_date',
            new_name='Finish',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='start_date',
            new_name='Start',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='Task',
        ),
    ]
