# Generated by Django 3.0.5 on 2021-03-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20210301_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='comments',
            new_name='certification',
        ),
    ]
